# Site settings
title: decodeuri
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  David Moulton, front end developer, blogs here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://decodeuri" # the base hostname & protocol for your site
twitter_username: davidcmoulton
github_username:  davidcmoulton

# Build settings
markdown: kramdown
